import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'

import AppProvider from '@/components/app-provider'
import { cn } from '@/lib/utils'
import { LocaleEnum } from '@/types/locales'

import '../globals.scss'

const beVietNamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--be-vietnam-pro',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { lang: LocaleEnum }
}>) {
  return (
    <html lang={params.lang}>
      <body className={cn(beVietNamPro.className, beVietNamPro.variable)}>
        <AppProvider>
          <div className="flex flex-1 flex-col">{children}</div>
          <Toaster />
        </AppProvider>
        {/* <DictionaryProvider dictionary={dictionary}> */}
        {/* <SidebarProvider> */}
        {/* <AppSidebar /> */}
        {/* <SidebarInset> */}
        {/* <Header dictionary={dictionary} /> */}

        {/* <Footer dictionary={dictionary} /> */}
        {/* </SidebarInset> */}
        {/* </SidebarProvider> */}
        {/* </DictionaryProvider> */}
      </body>
    </html>
  )
}
